# Generated by Django 3.1.1 on 2020-09-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address_state', models.CharField(max_length=255)),
                ('address_city', models.CharField(blank=True, max_length=255, null=True)),
                ('address_neighborhood', models.CharField(blank=True, max_length=255, null=True)),
                ('address_complement', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
